import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/component';

export const metadata: Metadata = {
  title: 'MeetProject',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
